[package]
name = "aoc2024"
version = "0.1.0"
edition = "2021"

[dependencies]
ahash = "0.8.11"
clap = { version = "4.5.21", features = ["derive"] }
divan = "0.1.16"
itertools = "0.13.0"
rand = "0.8.5"
regex = "1.11.1"

[[bench]]
name = "benchmarks"
harness = false
