[package]
name = "aoc2024"
version = "0.1.0"
edition = "2024"

[dependencies]
ahash = "0.8.11"
anyhow = "1.0.94"
clap = { version = "4.5.21", features = ["derive"] }
divan = "0.1.16"
itertools = "0.13.0"
nom = "7.1.3"
rand = "0.8.5"
regex = "1.11.1"

[[bench]]
name = "benchmarks"
harness = false
